<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>slim</string>
		<string>skim</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*([-%#\:\.\w\=].*)\s$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Ruby Slim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\s*)(ruby):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.ruby.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.ruby.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(javascript):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.javascript.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>source.js.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(---)\s*\n</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.frontmatter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(---)\s*\n</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.frontmatter.slim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.yaml.meta.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(coffee):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.coffeescript.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.coffeescript.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(markdown):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.markdown.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.markdown.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(css):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.css.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.css.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(sass):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.sass.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.sass.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sass</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(scss):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.scss.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.scss.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scss</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(less):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.less.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.less.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.less</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(erb):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.erb.filter.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.erb.filter.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.erb</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.prolog.slim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(! )($|\s.*)</string>
			<key>name</key>
			<string>meta.prolog.slim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(/)\s*.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.slash.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>comment.block.slim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=-)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?==+|~)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-attribute</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-ruby</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(\||')\s*</string>
			<key>comment</key>
			<string>Verbatim text (can include HTML tags and copied lines)</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\.|#|[-a-zA-Z0-9]+)([\w-]+)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.event.slim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>1 - dot OR hash OR any combination of word, number; 2 - OPTIONAL any combination of word, number, dash or underscore (following a . or</string>
			<key>end</key>
			<string>$|(?!\.|#|:|-|~|/|\}|\]|\*|\s?[\*\{])</string>
			<key>name</key>
			<string>meta.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(:[\w\d]+)+</string>
					<key>comment</key>
					<string>XML</string>
					<key>end</key>
					<string>$|\s</string>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:\s)(\.|#|[a-zA-Z0-9]+)([\w-]+)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.slim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.slim</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.event.slim</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Inline HTML / 1 - colon; 2 - dot OR hash OR any combination of word, number; 3 - OPTIONAL any combination of word, number, dash or underscore (following a . or</string>
					<key>end</key>
					<string>$|(?!\.|#|=|-|~|/|\}|\]|\*|\s?[\*\{])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#root-class-id-tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag-attribute</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\*\{)(?=.*\}|.*\|\s*$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Splat attributes</string>
					<key>end</key>
					<string>(\})|$|^(?!.*\|\s*$)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.ruby.embedded.slim</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#root-class-id-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
				<dict>
					<key>match</key>
					<string>/</string>
					<key>name</key>
					<string>punctuation.terminator.tag.slim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.escape.slim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\\.)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=\||')</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;[\w\d\:]+)</string>
			<key>comment</key>
			<string>Inline and root-level HTML tags</string>
			<key>end</key>
			<string>$|\/\&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>continuation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.slim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\\,])\s*\n</string>
		</dict>
		<key>delimited-ruby-a</key>
		<dict>
			<key>begin</key>
			<string>=\(</string>
			<key>end</key>
			<string>\)(?=( \w|$))</string>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>delimited-ruby-b</key>
		<dict>
			<key>begin</key>
			<string>=\[</string>
			<key>end</key>
			<string>\](?=( \w|$))</string>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>delimited-ruby-c</key>
		<dict>
			<key>begin</key>
			<string>=\{</string>
			<key>end</key>
			<string>\}(?=( \w|$))</string>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>embedded-ruby</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)#\{{1,2}</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}{1,2}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ruby.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>interpolated-ruby</key>
		<dict>
			<key>begin</key>
			<string>=(?=\b)</string>
			<key>end</key>
			<string>\s|\w$</string>
			<key>name</key>
			<string>source.ruby.embedded.html</string>
		</dict>
		<key>root-class-id-tag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.html</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\.|#)([\w\d\-]+)</string>
		</dict>
		<key>rubyline</key>
		<dict>
			<key>begin</key>
			<string>(==|=)(&lt;&gt;|&gt;&lt;|&lt;'|'&lt;|&lt;|&gt;)?|-</string>
			<key>comment</key>
			<string>Hack to thwart Sublime's Ruby highlighter. It thinks do without a variable continues the next line (this can be muted with a / at the end of the line). For things like yields, do is unnecessary without an argument, so this hack will suffice</string>
			<key>contentName</key>
			<string>source.ruby.embedded.slim</string>
			<key>end</key>
			<string>(do\s*\n$)|(?&lt;!\\|,|,\n|\\\n)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start-block.ruby</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.line.ruby.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Hack to let ruby comments work in this context properly</string>
					<key>match</key>
					<string>#.*$</string>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>(")(?=.*")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>(')(?=.*')</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-attribute</key>
		<dict>
			<key>begin</key>
			<string>([\w.#_-]+)(=)(?!\s)(true|false|nil)?(\s*\(|\{)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.event.slim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}|\)|$</string>
			<key>name</key>
			<string>meta.attribute-with-value.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-a</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.slim</string>
	<key>uuid</key>
	<string>36302CC1-1E76-4910-B7B6-F1915EBBA0D3</string>
</dict>
</plist>
